### ISSUE TITLE
no network after flashing anbox to nexus 5, ubuntu touch 16.04

### ISSUE THREAD

**Issue by chicoperico** [ubports/anbox#36] opened 2019-11-03 06:41 UTC
Good day to all!

I do have two Nexus-5 ubuntu touch devices, anbox was working on both of 
them.

Yesterday i ran a system upgrade on one of them, a complete reinstall on the other (because of 
other issues). The ubuntu touch version now is 16.04.

I then flashed the latest hammerhead anbox image onto the devices, as usual.
As a result all network functionality was lost, the phones could not connect to either the 
wifi-network or function as a telephone, they did not even recognise the SIM-card.

I tried sveral reinstallations on one of the phones, both ubuntu stable and edge, always with the 
same result.

They work normally, since i reinstalled ubuntu touch -  albeit without anbox, of course.

What now?

Rainer

**Comment by breiti-oi** [comment] 2019-11-24 19:51
Same here, also nexus 5 with latest stable ubtouch. Everything is working fine until I install the anbox-boot image.

**Comment by gsantner** [comment] 2019-12-04 20:13
This issue and issue <https://github.com/ubports/anbox/issues/36> <https://github.com/anbox/anbox/issues/1261>  seem to be duplicate of <https://github.com/ubports/ubuntu-touch/issues/1264> where a working solution is available from.
Do suggest to close this issue.

**Comment by Fuseteam** [comment] 2021-03-17 17:32
since we no longer need to flash the kernel on the nexus 5 this doesn't seem to be an issue anymore

**Closed as completed** 2021-05-28 12:18 UTC
